-- Italian 5-letter answer list for Wordle
-- 1629 words, accent-normalized (PERCHÉ -> PERCHE)
--
-- Two lists, as for English: this one holds words common enough to be a fair
-- answer, guesses_it.lua holds everything else accepted as a guess.
--
-- Words: 60000_parole_italiane.txt from https://github.com/napolux/paroleitaliane
-- (MIT License, Copyright (c) 2016 Francesco Napoletano).
-- Selected by frequency using it_50k.txt from
-- https://github.com/hermitdave/FrequencyWords (content CC BY-SA 4.0, built
-- from OpenSubtitles). Proper names, offensive words, letters not native to
-- Italian (J K W X Y), truncated forms (VEDER), articulated prepositions (DELLA)
-- and infinitive + pronoun forms (FARLO) were left out.
--
local words = {}
local raw = [[
ABATE,ABBIA,ABETE,ABILE,ABILI,ABITI,ABITO,ABUSA,ABUSI,ABUSO,ACETO,ACIDA,ACIDI,ACIDO,ACQUA
ACQUE,ACUTA,ACUTI,ACUTO,ADDII,ADDIO,ADORA,ADORI,ADORO,AEREA,AEREE,AEREI,AEREO,AGILE,AGILI
AGIRE,AGITA,AGITI,AGITO,AGLIO,AIUTA,AIUTI,ALGHE,ALITO,ALTRA,ALTRE,ALTRI,ALTRO,ALZAI,AMACA
AMANO,AMARA,AMARE,AMARI,AMARO,AMATE,AMATI,AMAVA,AMAVI,AMAVO,AMERA,AMICI,AMORI,AMPIE,AMPIO
ANCHE,ANDAI,ANIMA,ANIME,ANIMI,ANIMO,ANNOI,ANSIA,ANSIE,ANTRO,APICE,APRII,ARARE,ARCHI,ARDUA
ARIDA,ARIDO,AROMA,AROMI,ASCIA,ASILI,ASILO,ASINI,ASINO,ASPRA,ASPRO,ASTRI,ATOMI,ATOMO,ATRIO
AVARI,AVARO,AVERE,AVETE,AVEVA,AVEVI,AVEVO,AVIDA,AVIDI,AVIDO,AVRAI,AVREI,AVUTO,AVVIA,AVVIO
BABBI,BABBO,BACIA,BACIO,BAFFI,BAFFO,BAGNA,BAGNI,BAGNO,BALIA,BALLA,BALLI,BALLO,BALZO,BANCA
BANDA,BANDE,BARBA,BARBE,BARCA,BARRA,BARRE,BASSA,BASTA,BASTI,BASTO,BATTA,BATTE,BATTI,BATTO
BAULE,BAULI,BEATI,BECCO,BEFFA,BEFFE,BELLE,BELLI,BELVA,BELVE,BENDA,BENDE,BERRA,BERRO,BIMBA
BIMBE,BIMBI,BIMBO,BIRRA,BIRRE,BISCA,BOCCA,BOCCE,BOLLA,BOLLE,BOLLO,BOMBA,BOMBE,BONTA,BORDI
BORDO,BORGO,BORSA,BORSE,BOSCO,BOTTA,BOTTE,BOZZA,BOZZE,BRACE,BRAMA,BRANI,BRANO,BRAVA,BRAVE
BRAVI,BRAVO,BREVE,BREVI,BRODO,BRUCI,BRUCO,BRUNE,BRUNI,BRUTI,BUCCE,BUCHE,BUCHI,BUFFA,BUFFE
BUFFI,BUFFO,BUGIA,BUGIE,BULBI,BULBO,BUONA,BUONE,BUONI,BURRO,BUSSA,BUSSI,BUSSO,BUSTO,BUTTA
BUTTI,BUTTO,CACAO,CACCI,CADDE,CADDI,CADRA,CAFFE,CAGNA,CALCI,CALCO,CALDA,CALDE,CALDI,CALDO
CALLI,CALLO,CALMA,CALME,CALMI,CALMO,CALVA,CALVI,CALZA,CALZE,CAMBI,CAMPA,CAMPI,CAMPO,CANNA
CANNE,CANTA,CANTI,CANTO,CAPRA,CAPRE,CARNI,CARRI,CARRO,CARTA,CARTE,CASCO,CASSA,CASSE,CASTI
CAUSA,CAUSE,CAUSI,CAUSO,CAUTA,CAUTI,CAUTO,CEDRO,CELLA,CELLE,CENNI,CENNO,CENTO,CERCA,CERCO
CERTA,CERTE,CERTO,CERVO,CESSA,CESSI,CESTA,CESTI,CHINA,CICCA,CICLI,CICLO,CIECA,CIECO,CIELI
CIELO,CIFRA,CIFRE,CIGNI,CIGNO,CINTA,CIRCA,CIRCO,CISTE,CISTI,CITTA,CLIMA,COLLA,COLLE,COLLI
COLLO,COLMA,COLMI,COLMO,COLPA,COLPE,COLPI,COLPO,COLTA,COLTI,COLTO,CONTA,CONTE,CONTI,CONTO
COPIA,COPIE,COPRA,COPRE,COPRI,COPRO,CORDA,CORDE,CORNA,CORNO,CORPI,CORPO,CORRA,CORRE,CORRI
CORRO,CORSA,CORSE,CORTA,CORTE,CORTO,CORVO,COSCE,COSTA,COSTE,COSTI,COSTO,COTTA,COTTE,COTTI
COTTO,COZZA,COZZE,CREDA,CREDE,CREDI,CREDO,CREMA,CREME,CREPA,CREPE,CREPI,CRETA,CRISI,CROCI
CROMO,CRUDA,CRUDE,CRUDI,CRUDO,CULLA,CULTO,CUOCA,CUOCO,CUOIO,CUORE,CUORI,CURVA,CURVE,CURVO
DACCI,DALLO,DAMMI,DANDO,DANNI,DANNO,DANZA,DANZE,DANZO,DARAI,DAREI,DATTI,DEBBA,DEBBO,DEGNE
DEGNI,DEGNO,DENSA,DENSO,DENTE,DENTI,DESSE,DESSI,DESTA,DESTI,DETTA,DETTE,DETTI,DETTO,DIAMO
DIARI,DICCI,DIECI,DIEDE,DIEDI,DIETA,DIETE,DIGHE,DIGLI,DILLE,DIMMI,DIRAI,DIREI,DISCO,DISSE
DISSI,DISTA,DOCCE,DOLCE,DOLCI,DONNA,DONNE,DOPPI,DORMA,DORME,DORMO,DORSO,DOTTO,DOVRA,DOVRO
DUBBI,DUOMO,EBANO,EBETE,EBREA,EBREE,EBREI,EBREO,ELICA,ELOGI,ELUSO,EMANA,ENTRA,ENTRI,ENTRO
EPICA,EPICO,EPOCA,ERANO,EREDE,EREDI,ESAME,ESAMI,ESCHE,ESIGE,ESILE,ESITI,ESITO,ETERE,EVITI
EVITO,FACCE,FACCI,FAGLI,FALCE,FALLA,FALLE,FALLI,FALLO,FALSA,FALSE,FALSI,FALSO,FAMMI,FANGO
FANNE,FANNO,FANTE,FANTI,FARAI,FAREI,FASCE,FASCI,FATTA,FATTE,FATTI,FATTO,FERIE,FERME,FESSI
FESSO,FESTA,FESTE,FETTA,FETTE,FICHI,FIENO,FIERA,FIERE,FIERI,FIGLI,FINGE,FINGI,FINGO,FINII
FINTO,FIRME,FISCO,FISSA,FISSE,FISSI,FISSO,FITTA,FITTE,FITTO,FIUMI,FIUTA,FIUTO,FOCHE,FOGLI
FOGNA,FOGNE,FOLLA,FOLLE,FOLTA,FOLTI,FONDA,FONDI,FONDO,FORMA,FORME,FORNI,FORNO,FORSE,FORZA
FORZE,FOSSA,FOSSE,FOSSI,FOSTE,FOSTI,FRANA,FRASE,FRASI,FRATE,FRATI,FRENI,FRENO,FRODI,FRODO
FRUGA,FUGGA,FUGGE,FUGGI,FUGHE,FUMMO,FUNGE,FUNGO,FUOCO,FUORI,FURBA,FURBE,FURBI,FURBO,FURTO
FUSTI,FUSTO,GALLI,GAMBA,GAMBE,GAMBO,GAMMA,GANCI,GARBO,GARZA,GARZE,GEMME,GENTE,GERGO,GERME
GESSO,GESTI,GESTO,GETTA,GETTI,GETTO,GIACE,GIGLI,GIOCA,GIOCO,GIOGO,GIOIE,GIOVA,GIRAI,GIURA
GIURI,GIURO,GLOBO,GOBBA,GOBBO,GOCCE,GOFFA,GOFFO,GOLFO,GOMMA,GOMME,GONFI,GONNA,GONNE,GRADI
GRANA,GRANE,GRANI,GRANO,GRATE,GRATI,GRAVA,GRAVE,GRAVI,GRIDA,GRIDI,GRIDO,GRIGI,GUAIO,GUIDE
GUIDI,GUSCI,GUSTA,GUSTI,GUSTO,HANNO,IDOLI,IMITA,INIZI,INVIA,INVII,INVIO,IODIO,ISOLE,LACCA
LACCI,LADRA,LADRI,LADRO,LAGHI,LAMPI,LAMPO,LANCE,LANCI,LANDE,LARDO,LARGA,LARGO,LASCI,LATTA
LATTE,LEALI,LECCA,LECCO,LEGGA,LEGGE,LEGGI,LEGGO,LEGHE,LEGHI,LEGNA,LEGNO,LEMBO,LENTA,LENTE
LENTI,LENTO,LENZA,LEONI,LEPRE,LEPRI,LESSE,LESSI,LESSO,LETTA,LETTE,LETTI,LETTO,LIBRE,LIBRI
LIBRO,LICEO,LIETI,LIEVE,LIEVI,LINEA,LINEE,LISCA,LISCI,LISTA,LISTE,LITRI,LITRO,LORDE,LORDO
LOSCA,LOSCO,LOTTA,LOTTE,LOTTI,LOTTO,LUNGA,LUNGO,LUOGO,LUSSO,LUTTO,MADRE,MADRI,MAGRA,MAGRE
MAGRI,MAGRO,MAMMA,MAMME,MANCA,MANCE,MANCO,MANDA,MANDI,MANDO,MANGI,MANIE,MANZI,MANZO,MAPPA
MAPPE,MARCE,MAREA,MAREE,MARMO,MARZO,MASSA,MASSE,MASSI,MASSO,MATTA,MATTE,MATTI,MATTO,MAZZA
MAZZE,MAZZI,MAZZO,MEDIA,MEDIE,MEDIO,MELMA,MENSA,MENTA,MENTE,MENTI,MENTO,MERCE,MESSA,MESSE
MESSI,MESSO,METRI,METRO,METTA,METTE,METTI,METTO,MEZZA,MEZZE,MEZZI,MEZZO,MIELE,MILLE,MILZA
MIOPE,MIRAI,MISTA,MISTE,MISTI,MISTO,MOGLI,MOLLA,MOLLE,MOLTA,MOLTE,MOLTI,MOLTO,MONDI,MONTA
MONTE,MONTI,MONTO,MORDA,MORSA,MORSE,MORSO,MORTA,MORTE,MORTO,MOSCA,MOSSA,MOSSE,MOSSI,MOSSO
MOZZO,MUCCA,MUFFA,MULTA,MULTE,MUOIA,MUOIO,MUORE,MUORI,MUOVA,MUOVE,MUOVI,MUOVO,MUSEI,MUSEO
NAFTA,NARRA,NASCE,NEGHI,NEGRI,NERVO,NONNA,NONNE,NONNI,NONNO,NORME,NOTAI,NOTTE,NOTTI,NOZZE
NUORA,NUOTA,NUOTI,NUOTO,NUOVA,NUOVE,NUOVI,NUOVO,NUTRE,NUTRI,OBLIO,OCCHI,ODORA,ODORE,ODORI
OFFRA,OFFRE,OFFRI,OFFRO,OLIVE,OLTRE,OMBRE,ONCIA,ONORI,OPERA,OPERE,OPERI,OPERO,OPPIO,ORALE
ORALI,ORARI,ORCHI,ORMAI,OSANO,OSARE,OSATE,OSATO,OVALE,OVILE,OVVIA,OVVIO,PACCO,PADRE,PADRI
PAESE,PAESI,PAGHI,PALCO,PALLA,PALLE,PALME,PANCA,PANCE,PANNA,PANNE,PANNI,PANNO,PAPPA,PARCO
PARSA,PARSO,PARTE,PARTO,PARVE,PASSA,PASSI,PASSO,PASTA,PASTE,PASTI,PASTO,PATTA,PATTI,PATTO
PAURA,PAURE,PAUSA,PAUSE,PAZZA,PAZZE,PAZZI,PAZZO,PECCA,PEGNI,PEGNO,PELLE,PELLI,PENDE,PENNA
PENNE,PENSA,PENSI,PENSO,PERDE,PERNO,PERSA,PERSE,PERSO,PESCA,PESCE,PESCI,PESCO,PESTE,PESTI
PESTO,PETTI,PETTO,PEZZA,PEZZE,PEZZI,PEZZO,PIACE,PIACI,PIAGA,PIANA,PIANI,PIANO,PICCO,PIEDE
PIEDI,PIEGA,PIENA,PIENE,PIENI,PIENO,PIGLI,PIGRA,PIGRI,PIGRO,PINNA,PINNE,PINTA,PINTE,PINZA
PINZE,PIOVE,PISTA,PISTE,PIUMA,PIUME,PIZZA,PIZZE,PIZZO,PLEBE,POCHE,POCHI,PODIO,POEMA,POETA
POETI,POLLI,POLLO,POLPA,POLSI,POLSO,POMPA,POMPE,PONTE,PONTI,POPPA,POPPE,PORGE,PORRE,PORRI
PORRO,PORTA,PORTE,PORTO,POSSA,POSSO,POSTA,POSTE,POSTI,POSTO,POTEI,POTRA,POZZA,POZZE,POZZI
POZZO,PRATI,PRATO,PREDA,PREDE,PREGA,PREGI,PREGO,PREMA,PREME,PREMI,PREMO,PRESA,PRESE,PRESI
PRESO,PRETE,PRETI,PRIME,PRIMI,PRIVA,PRIVE,PRIVI,PRIVO,PRODE,PRODI,PROLE,PROSA,PROVA,PROVE
PROVI,PROVO,PUGNI,PUGNO,PULCE,PULCI,PULSA,PUNGE,PUNTA,PUNTE,PUNTI,PUNTO,PUZZA,PUZZI,PUZZO
QUALE,QUALI,QUASI,QUOTA,QUOTE,RAGGI,RAGNI,RAGNO,RAMPA,RAMPE,RANGO,RASOI,RATTI,RATTO,RAZZA
RAZZE,RAZZI,RAZZO,REALI,REATI,REATO,RECHI,REGGE,REGGI,REGGO,REGNA,REGNI,REGNO,RENDA,RENDE
RENDI,RENDO,RENNA,RENNE,RESSA,RESTA,RESTI,RESTO,RETRO,RETTA,RETTE,RIGHE,RISSA,RISSE,RITMI
RITMO,ROCCE,ROMBO,ROMPA,ROMPE,ROMPI,ROMPO,RONDA,RONDE,RONZA,ROSPI,ROSPO,ROSSE,ROTTA,ROTTE
ROTTI,ROTTO,ROZZA,ROZZI,ROZZO,RUGHE,RULLO,RUOLI,RUOLO,RUOTA,RUOTE,RUPPE,RUSSA,RUSSI,SACCA
SACCO,SACRA,SACRE,SACRI,SACRO,SAGGE,SAGGI,SALDA,SALDI,SALDO,SALGA,SALMA,SALMI,SALMO,SALPA
SALSA,SALSE,SALTA,SALTI,SALTO,SALVI,SANNO,SAPPI,SARAI,SAREI,SARTA,SARTO,SASSI,SASSO,SAZIA
SAZIO,SBAVA,SCADE,SCAFO,SCALA,SCALE,SCALO,SCAVA,SCAVI,SCAVO,SCEMA,SCEME,SCEMI,SCEMO,SCENA
SCENE,SCESA,SCESE,SCESI,SCESO,SCOLO,SCOPA,SCOPE,SCOPI,SCOPO,SCUDI,SCUDO,SCURA,SCURE,SCURI
SCURO,SCUSA,SCUSE,SCUSI,SCUSO,SECCA,SECCO,SEDIA,SEDIE,SEGGI,SEGHE,SEGNA,SEGNI,SEGNO,SEGUA
SEGUE,SEGUI,SEGUO,SELLA,SENNO,SENSI,SENSO,SENTA,SENTE,SENTI,SENTO,SENZA,SEPPE,SEPPI,SERBA
SERBI,SERBO,SERIA,SERIE,SERIO,SERRA,SERRE,SERVA,SERVE,SERVO,SESSI,SESSO,SETTA,SETTE,SFERA
SFERE,SFIDA,SFIDE,SFIDI,SFIDO,SFILA,SFOGA,SFOGO,SIAMO,SIANO,SIATE,SIDRO,SIEDA,SIEDE,SIEDI
SIEDO,SIEPE,SIEPI,SIERO,SIETE,SIGLA,SMISE,SMISI,SOAVE,SOBRI,SOCIO,SODIO,SOFFI,SOGNA,SOGNI
SOGNO,SOLCO,SOMMA,SOMME,SOMMO,SONDA,SONDE,SONNI,SONNO,SOPRA,SORDA,SORDI,SORDO,SORGE,SORSO
SORTA,SORTE,SORTO,SOSIA,SOSTA,SOSTE,SOTTO,SPADA,SPADE,SPAGO,SPARA,SPARI,SPARO,SPAZI,SPESA
SPESE,SPESI,SPESO,SPIGA,SPINA,SPINE,SPIRO,SPOSA,SPOSE,SPOSI,SPOSO,SPUTA,SPUTI,SPUTO,STADI
STARE,STARO,STATA,STATE,STATI,STATO,STAVA,STAVI,STAVO,STELO,STESA,STESE,STESI,STESO,STILE
STILI,STIMA,STIME,STIMO,STIRA,STIRO,STIVA,STUDI,STUFA,STUFI,STUFO,SUCCO,SULLO,SUOLA,SUOLE
SUONA,SUONI,SUONO,SUORA,SUORE,SVAGO,TACCO,TAGLI,TALCO,TALPA,TALPE,TANFO,TANGA,TANTA,TANTE
TANTI,TANTO,TAPPA,TAPPE,TAPPI,TAPPO,TARDA,TARDI,TARDO,TARGA,TASCA,TASSA,TASSE,TASSI,TASSO
TASTI,TASTO,TATTO,TAZZA,TAZZE,TEMPI,TEMPO,TENDA,TENDE,TENGA,TENGO,TENIA,TENNE,TENNI,TENTA
TENTI,TENTO,TENUE,TERME,TERRA,TERRE,TESSA,TESTA,TESTE,TESTI,TESTO,TETRA,TETRO,TETTI,TETTO
TIBIA,TIENE,TIENI,TIGRE,TIGRI,TINTA,TINTE,TINTI,TINTO,TIRAI,TIZIA,TOCCA,TOCCO,TOGLI,TOLGA
TOLGO,TOLSE,TOLTA,TOLTE,TOLTI,TOLTO,TOMBA,TOMBE,TONDA,TONDI,TONDO,TONFO,TONNO,TONTA,TONTI
TONTO,TOPPA,TORCE,TORNA,TORNI,TORNO,TORRE,TORRI,TORTA,TORTE,TORTO,TOSSE,TOSTA,TOSTE,TOSTI
TOSTO,TOZZO,TRAMA,TRAME,TRAVE,TRAVI,TREMA,TREMI,TREMO,TRENI,TRENO,TRITA,TRONO,TROTA,TROTE
TROVA,TROVI,TROVO,TUFFI,TUFFO,TUONI,TUONO,TURBA,TURBO,TURNI,TURNO,TUTTA,TUTTE,TUTTI,TUTTO
UDIRE,UDITE,UDITO,ULULA,UMANA,UMANE,UMANI,UMANO,UMIDA,UMIDE,UMIDI,UMIDO,UMILI,UMORE,UMORI
UNICI,UNIRE,UNITA,UNITE,UNITI,UNITO,USANO,USARE,USATA,USATE,USATI,USATO,USAVA,USAVI,USAVO
USCII,USCIO,USINO,USURA,UTILE,UTILI,VACCA,VAGHE,VAGHI,VAGLI,VALGA,VALGO,VALLE,VALLI,VALLO
VANGA,VANTA,VANTI,VANTO,VARCO,VARIE,VASCA,VASTA,VASTE,VASTO,VEDRA,VEGLI,VENDA,VENDE,VENDI
VENDO,VENGA,VENNE,VENNI,VENTI,VENTO,VERBI,VERBO,VERDE,VERDI,VERGA,VERME,VERRA,VERSA,VERSO
VESPA,VESPE,VESTE,VESTI,VESTO,VETRI,VETTA,VETTE,VIALE,VIBRA,VIDEO,VIENE,VIENI,VIETA,VIGNA
VILLE,VINCE,VINCI,VINCO,VINTA,VINTE,VINTI,VINTO,VIOLE,VIOLI,VIRTU,VISSE,VISTA,VISTE,VISTI
VISTO,VITTO,VIZIO,VOLGE,VOLLE,VOLLI,VOLPE,VOLPI,VOLTA,VOLTE,VOLTI,VOLTO,VORRA,VUOLE,VUOTA
VUOTE,VUOTI,VUOTO,ZAINI,ZAINO,ZAMPA,ZAMPE,ZANNA,ZANNE,ZAPPA,ZECCA,ZEPPA,ZEPPO,ZITTA,ZITTE
ZITTI,ZITTO,ZOLFO,ZOPPA,ZOPPO,ZUCCA,ZUFFA,ZUPPA,ZUPPE
]]
for w in raw:gmatch("[A-Z]+") do
    words[#words + 1] = w
end
return words
